base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("home.urls")),
    path("admin/", admin.site.urls),
    path("data-browser/", include("data_browser.urls")),
    path("silk/", include("silk.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.home, name="home"),
    path("call-records/", views.call_records_list, name="call-records"),
    path("call-records/create", views.call_record_create, name="call-records-create"),
    path(
        "call-records/delete-all",
        views.call_records_delete_all,
        name="call-records-delete-all",
    ),
    path("prospects/", views.prospects_list, name="prospects-list"),
    path(
        "prospects/delete-all", views.prospects_delete_all, name="prospects-delete-all"
    ),
    path(
        "prospects/import-excel",
        views.prospects_import_excel,
        name="prospects-import-excel",
    ),
    path(
        "prospects/<int:prospect_id>/add-call",
        views.prospects__call_record_create,
        name="prospects--call-record-create",
    ),
    # HTMX
    path("htmx/<str:action>", views.htmx_test, name="htmx"),
]

home/models.py
from django.db import models


class Prospect(models.Model):
    """
    prospect's business details
    """

    PROVINCE_CHOICES = [
        ("AB", "Alberta"),
        ("BC", "British Columbia"),
        ("MB", "Manitoba"),
        ("NB", "New Brunswick"),
        ("NL", "Newfoundland and Labrador"),
        ("NT", "Northwest Territories"),
        ("NS", "Nova Scotia"),
        ("NU", "Nunavut"),
        ("ON", "Ontario"),
        ("PE", "Prince Edward Island"),
        ("QC", "Quebec"),
        ("SK", "Saskatchewan"),
        ("YT", "Yukon"),
    ]

    class ExistenceChoices(models.TextChoices):
        EXISTS = "exists"
        DOES_NOT_EXIST = "does_not_exist"
        UNKNOWN = "unknown"

    business_name = models.CharField(max_length=255, null=True, blank=True)
    industry = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20, unique=True, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    province = models.CharField(
        choices=PROVINCE_CHOICES, max_length=2, null=True, blank=True
    )
    street_address = models.CharField(max_length=255, null=True, blank=True)
    website_url = models.URLField(blank=True, null=True, max_length=255)
    yellow_pages_link = models.URLField(blank=True, null=True, max_length=255)

    existence_status = models.CharField(
        choices=ExistenceChoices, default=ExistenceChoices.UNKNOWN, max_length=20
    )
    """Does business still exist?"""

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def has_been_called(self) -> bool:
        """
        Check if the prospect has been called.

        This property returns True if there is at least one ColdCallRecord
        associated with the Prospect, and False otherwise.

        Returns:
            bool: True if the prospect has been called, False otherwise.
        """
        return self.coldcallrecord_set.exists()

    @property
    def had_owner_conversation(self) -> bool:
        """
        Check if any of the call records for the prospect had a conversation.

        This property returns True if there is at least one ColdCallRecord
        associated with the Prospect where had_conversation is True, and False otherwise.

        Returns:
            bool: True if any of the call records for the prospect had a conversation, False otherwise.
        """
        return self.coldcallrecord_set.filter(had_owner_conversation=True).exists()

    def __str__(self) -> str:
        return str(self.business_name)


class ColdCallRecord(models.Model):
    """
    record track of a cold call
    """

    OUTCOME_CHOICES = [
        ("no", "no"),
        ("yes", "yes"),
        ("meeting", "meeting"),
    ]

    PICK_UP_STATUS_CHOICES = [
        ("yes", "yes"),
        ("no", "no"),
        ("ivr", "ivr"),
        ("voicemail", "voicemail"),
        ("not connecting", "not connecting"),
    ]

    date = models.DateTimeField(null=True, blank=True)
    pick_up_status = models.CharField(
        choices=PICK_UP_STATUS_CHOICES,
        default="no",
        blank=True,
        null=True,
        max_length=255,
    )
    had_owner_conversation = models.BooleanField()
    outcome = models.CharField(
        choices=OUTCOME_CHOICES, blank=True, null=True, max_length=255
    )
    prospect = models.ForeignKey(Prospect, on_delete=models.PROTECT, null=True)
    my_area_code_city = models.CharField(
        max_length=100,
        blank=True,
        null=True,
        default="Toronto",
    )
    product_selling = models.CharField(max_length=255, null=True, blank=True)
    opening = models.CharField(max_length=255, blank=True, null=True)
    objection = models.CharField(max_length=255, blank=True, null=True)
    note = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.prospect} - {self.call_time}"

home/forms.py
from django import forms
from django.core.exceptions import ValidationError

from . import services
from .models import ColdCallRecord, Prospect


class ImportXlsxForm(forms.ModelForm):
    """
    Form for uploading a excel file.
    """

    excel_file = forms.FileField()

    class Meta:
        model = Prospect
        fields = ["excel_file", "industry"]

    def clean_excel_file(self):
        excel_file = self.cleaned_data.get("excel_file")
        if not services.is_xlsx(excel_file):
            raise ValidationError("Must be an excel file")

        if not services.validate_yellow_pages_ca_excel_columns(excel_file=excel_file):
            raise ValidationError("Columns are not correct")

        return excel_file


class YellowPagesCaHtmlForm(forms.Form):
    """
    For for pasting yellow pages canada page to import
    prospects data
    """

    html = forms.CharField(widget=forms.Textarea)


class CallRecordForm(forms.ModelForm):
    """
    Create call record
    """

    class Meta:
        model = ColdCallRecord
        exclude = ["created_at", "updated_at"]
        widgets = {
            "date": forms.DateTimeInput(attrs={"type": "datetime"}),
            "outcome": forms.RadioSelect(attrs={"class": "btn-check"}),
        }


class ProspectsFilterForm(forms.ModelForm):
    class Meta:
        model = Prospect
        fields = ["province"]

home/views.py
import datetime
import datetime as dt

from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Exists, OuterRef
from django.http import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, redirect, render

from . import filters, services
from .forms import CallRecordForm, ImportXlsxForm
from .models import ColdCallRecord, Prospect


def home(request):
    return render(request, "home/home.html")


def prospects_list(request):
    prospects = Prospect.objects.prefetch_related("coldcallrecord_set").annotate(
        called=Exists(ColdCallRecord.objects.filter(prospect_id=OuterRef("pk"))),
        conversation=Exists(
            ColdCallRecord.objects.filter(
                prospect_id=OuterRef("pk"), had_owner_conversation=True
            )
        ),
    )

    prospects_filter = filters.ProspectsFilter(request.GET, queryset=prospects)

    paginator = Paginator(prospects_filter.qs, 10)
    page_number = request.GET.get("page")
    prospects_paginated = paginator.get_page(page_number)
    context = {
        "prospects_paginated": prospects_paginated,
        "prospects_filter": prospects_filter,
        "prospects_filtered_count": prospects_filter.qs.count(),
        "outcome_no_count": services.calls_outcome_no_count(),
        "total_calls_count": services.calls_total_count(),
        "calls_today": services.calls_today_count(),
        "prospects_total_count": services.prospects_total_count(),
        "local_times": services.get_city_local_times(),
    }
    return render(request, "home/prospects.html", context)


def prospects_delete_all(request):
    Prospect.objects.all().delete()
    return redirect("home:prospects-list")


def prospects_import_excel(request):
    if request.method == "POST":
        import_excel_form = ImportXlsxForm(request.POST, request.FILES)
        if import_excel_form.is_valid():
            industry = import_excel_form.cleaned_data["industry"]
            excel_file = request.FILES["excel_file"]
            services.import_prospects_from_excel(
                excel_file=excel_file, industry=industry
            )
            messages.success(request, "Prospects imported")
            return redirect("home:prospects-list")
    else:
        import_excel_form = ImportXlsxForm()

    context = {"import_excel_form": import_excel_form}
    return render(request, "home/prospects_import_excel.html", context)


def prospects__call_record_create(request, prospect_id):
    prospect = get_object_or_404(Prospect, id=prospect_id)

    if request.method == "POST":
        call_record_form = CallRecordForm(request.POST)
        if call_record_form.is_valid():
            call_record_form.save()
            next_url = request.GET.get("next")
            return redirect(next_url or "home:prospects-list")
    else:
        call_record_form = CallRecordForm(
            initial={
                "date": dt.datetime.now(datetime.UTC),
                "prospect": prospect,
                "my_area_code_city": "Toronto",
            }
        )

    context = {"call_record_form": call_record_form, "prospect": prospect}
    return render(
        request,
        "home/prospects__add_call.html",
        context,
    )


def call_records_list(request):
    call_records = ColdCallRecord.objects.all()
    context = {"call_records": call_records}
    return render(request, "home/call_records.html", context)


def call_record_create(request):
    if request.method == "POST":
        call_record_form = CallRecordForm(request.POST)
        if call_record_form.is_valid():
            call_record_form.save()
            next_url = request.GET.get("next")
            if next_url:
                return redirect(next_url)
            return redirect("home:call-records")
    else:
        prospect_id = request.GET.get("prospect_id")
        prospect = None
        if prospect_id:
            prospect = get_object_or_404(Prospect, id=prospect_id)

        call_record_form = CallRecordForm(
            initial={
                "date": dt.date.today(),
                "prospect": prospect,
                "my_area_code_city": "Toronto",
                "outcome": "no",
            }
        )

    return render(
        request,
        "home/call_records_create.html",
        {"call_record_form": call_record_form},
    )


def call_records_delete_all(request):
    ColdCallRecord.objects.all().delete()
    return redirect("home:call-records")


def htmx_test(request, action: str):
    match action:
        case "update_existence_status":
            existence_status = request.GET.get("existence_status")
            prospect_id = request.GET.get("prospect_id")
            if not existence_status:
                return HttpResponseBadRequest("existence_status is not in query param")
            if not prospect_id:
                return HttpResponseBadRequest("prospect_id is not in query param")

            prospect = Prospect.objects.get(id=prospect_id)
            prospect.existence_status = existence_status
            prospect.full_clean()
            prospect.save()

            context = {"existence_status": existence_status}
            return render(request, "home/htmx/test.html", context)

        case _:
            return HttpResponseBadRequest(f"invalid action: {action}")

home/templates/home/_navigation.html
{% load active_link_tags %}
<nav>
    <div class="list-group">
        <a class="list-group-item list-group-item-action {% active_link 'home:call-records' %}"
           href="{% url 'home:call-records' %}">Call Records</a>
        <a class="list-group-item list-group-item-action {% active_link 'home:prospects-list' %}"
           href="{% url 'home:prospects-list' %}">Prospects</a>
    </div>
</nav>

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Title</title>
        <link rel="icon" type="image/png" href="data:image/png;base64,iVBORw0KGgo=">
        <link rel="stylesheet"
              type="text/css"
              href="{% static 'home/custom.css' %}">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <script src="https://unpkg.com/htmx.org@1.9.11"></script>
        {#  bootstrap table#}
        <link rel="stylesheet"
              href="https://unpkg.com/bootstrap-table@1.22.4/dist/bootstrap-table.min.css">
        <link rel="stylesheet" href="{% static 'home/custom.css' %}">
    </head>
    <body data-bs-theme="light" class="bg-light">
        <header>
            <nav class="navbar navbar-expand-sm bg-body-secondary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
                    <button class="navbar-toggler"
                            type="button"
                            data-bs-toggle="offcanvas"
                            data-bs-target="#drawer"
                            aria-controls="navbarSupportedContent"
                            aria-expanded="false"
                            aria-label="Toggle drawer">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
            </nav>
        </header>
        <div class="d-flex" id="body">
            <aside class="d-none d-sm-block p-3" id="sidebar">
                <div class="vstack gap-3">
                    {% block navigation %}
                        {% include 'home/_navigation.html' %}
                    {% endblock navigation %}
                    <nav>
                        <button class="btn" data-bs-toggle="collapse" data-bs-target="#admin-nav">
                            <i class="bi bi-chevron-down"></i> More
                        </button>
                        <div class="list-group collapse" id="admin-nav">
                            <a class="list-group-item list-group-item-action"
                               href="{% url 'admin:index' %}">Admin</a>
                            <a class="list-group-item list-group-item-action"
                               href="{% url 'data_browser:home' %}">Data
                            Browser</a>
                            <a class="list-group-item list-group-item-action"
                               href="{% url 'silk:summary' %}">Silk</a>
                            <a class="list-group-item list-group-item-action"
                               href="https://docs.google.com/spreadsheets/d/1BdteY0x-T5d4VVbsKJQxTqDyqdH_gkSk">Gsheet</a>
                            <a class="list-group-item list-group-item-action" href="upnote://">UpNote</a>
                        </div>
                    </nav>
                </div>
            </aside>
            <main class="container py-2" id="content">
                {% block content %}
                    cold calls content
                {% endblock content %}
            </main>
        </div>
        <div id="drawer" class="offcanvas offcanvas-start">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="drawer-header">Offcanvas</h5>
                <button type="button"
                        class="btn-close"
                        data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <div class="vstack gap-3">
                    {% block drawer %}
                        {% include 'home/_navigation.html' %}
                    {% endblock drawer %}
                    <nav>
                        <div class="list-group">
                            <a class="list-group-item list-group-item-action"
                               href="{% url 'admin:index' %}">Admin</a>
                            <a class="list-group-item list-group-item-action"
                               href="{% url 'data_browser:home' %}">Data
                            Browser</a>
                            <a class="list-group-item list-group-item-action"
                               href="{% url 'silk:summary' %}">Silk</a>
                            <a class="list-group-item list-group-item-action"
                               href="https://docs.google.com/spreadsheets/d/1BdteY0x-T5d4VVbsKJQxTqDyqdH_gkSk">Gsheet</a>
                            <a class="list-group-item list-group-item-action" href="upnote://">UpNote</a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
                crossorigin="anonymous"></script>
        <script src="https://unpkg.com/bootstrap-table@1.22.4/dist/bootstrap-table.min.js"></script>
    </body>
</html>

home/templates/home/call_records.html
{% extends 'home/base.html' %}
{% block content %}
    <a href="{% url 'home:call-records-create' %}" class="btn btn-primary">New</a>
    <a href="{% url 'home:call-records-delete-all' %}"
       class="btn btn-danger"
       onclick="return confirm('Do you really want to delete calls')">Delete Calls</a>
{% endblock content %}

home/templates/home/call_records_create.html
{% extends 'home/base.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ call_record_form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

home/templates/home/home.html
{% extends 'home/base.html' %}
{% block content %}
    cold calls home
{% endblock content %}

home/templates/home/prospects.html
{% extends 'home/base.html' %}
{% load crispy_forms_filters %}
{% load widget_tweaks %}
{% block content %}
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="{% if message.tags %}alert alert-{{ message.tags }}{% endif %}">{{ message }}</div>
            {% endfor %}
        </div>
    {% endif %}
    {# stats #}
    <div>
        <small>Vancouver: {{ local_times.vancouver }}</small> |
        <small>Edmonton: {{ local_times.edmonton }}</small> |
        <small>Winnipeg: {{ local_times.winnipeg }}</small> |
        <small>Toronto: {{ local_times.toronto }}</small> |
        <small>Halifax: {{ local_times.halifax }}</small> |
    </div>
    <div>
        <small>NOs: {{ outcome_no_count }}</small> |
        <small>Calls total: {{ total_calls_count }}</small> |
        <small>Calls today: {{ calls_today }}</small> |
        <small>Prospects total: {{ prospects_total_count }}</small> |
        <small>Prospects filtered: {{ prospects_filtered_count }}</small>
    </div>
    {# stats end #}
    {# filters start #}
    <button class="btn btn-sm"
            data-bs-toggle="collapse"
            data-bs-target="#filters">
        Filter <i class="bi bi-filter"></i>
    </button>
    <div class="collapse" id="filters">
        <div class="card card-body">
            <form>
                {{ prospects_filter.form|crispy }}
                <button class="btn btn-secondary">Apply</button>
            </form>
        </div>
    </div>
    {# filters end #}
    {#    prospect loop#}
    <div class="vstack gap-4 mt-3">
        {% for prospect in prospects_paginated %}
            <div class="card">
                <div class="card-body">
                    <div class="vstack gap-2">
                        <p class="card-text">
                            <span>Name: {{ prospect.business_name }}</span>
                            <br>
                            <span>City: {{ prospect.city }}</span>
                            <br>
                            <span>Industry: {{ prospect.industry }}</span>
                            <br>
                        <span> Web: <a href="{{ prospect.website_url }}" target="_blank">{{ prospect.website_url }}</a>
                    </span>
                    <br>
                <span> YP: <a href="{{ prospect.yellow_pages_link }}" target="_blank">Yellow Pages</a>
            </span>
        </p>
        <p class="card-text">
            <span>Phone:</span>
            <br>
            <span>{{ prospect.phone_number }}</span>
        </p>
        {# badges #}
        <div>
            {% if prospect.had_owner_conversation %}
                <span class="badge text-bg-success rounded-pill">Had conversation</span>
            {% endif %}
            {% if prospect.has_been_called %}<span class="badge text-bg-warning rounded-pill">Called</span>{% endif %}
        </div>
        <a class="btn btn-primary d-block"
           href="{% url 'home:prospects--call-record-create' prospect_id=prospect.id %}?next={{ request.get_full_path|urlencode }}">
            Make a call <i class="bi bi-arrow-right"></i>
        </a>
    </div>
</div>
</div>
{% endfor %}
</div>
{#end prospects loop#}
{# prospects pagination #}
<nav aria-label="Page navigation">
    <ul class="pagination">
        {% if prospects_paginated.has_previous %}
            <li class="page-item">
                <a class="page-link"
                   href="?{{ request.GET.urlencode }}&page={{ prospects_paginated.previous_page_number }}">Previous</a>
            </li>
        {% endif %}
        {% if prospects_paginated.has_next %}
            <li class="page-item">
                <a class="page-link"
                   href="?{{ request.GET.urlencode }}&page={{ prospects_paginated.next_page_number }}">Next</a>
            </li>
        {% endif %}
    </ul>
</nav>
<hr>
<div class="vstack gap-1 mt-2">
    {#  import excel form #}
    <a class="btn btn-secondary"
       href="{% url 'home:prospects-import-excel' %}">
        Import Excel <i class="bi bi-filetype-xlsx"></i>
    </a>
    {# delete all prospects #}
    <a class="btn btn-danger"
       href="{% url 'home:prospects-delete-all' %}"
       onclick="return confirm('Do you really want to delete prospects')">Delete Prospects</a>
</div>
{% endblock content %}

home/templates/home/prospects__add_call.html
{% extends 'home/base.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <a href="tel:{{ prospect.phone_number }}">
        <span class="fs-4">
            <i class="bi bi-telephone">&nbsp;&nbsp;</i> {{ prospect.phone_number }}
        </span>
    </a>
    <div class="hstack justify-content-between">
        <div class="d-inline">
            Prospect exists:
            <span id="exists_status">{{ prospect.existence_status }}</span>
            <span id="indicator" class="htmx-indicator spinner-border"></span>
        </div>
        <div>
            <button hx-get="{% url 'home:htmx' action='update_existence_status' %}?existence_status=exists&prospect_id={{ prospect.id }}"
                    hx-trigger="click"
                    hx-target="#exists_status"
                    hx-indicator="#indicator"
                    hx-disabled-elt="this"
                    class="btn btn-success">Yes</button>
            <button hx-get="{% url 'home:htmx' action='update_existence_status' %}?existence_status=does_not_exist&prospect_id={{ prospect.id }}"
                    hx-trigger="click"
                    hx-target="#exists_status"
                    hx-indicator="#indicator"
                    hx-disabled-elt="this"
                    class="btn btn-danger">No</button>
        </div>
    </div>
    <form method="post">
        <div class="vstack gap-2">
            {% csrf_token %}
            {{ call_record_form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
{% endblock content %}

home/templates/home/prospects_import_excel.html
{% extends 'home/base.html' %}
{% load crispy_forms_filters %}
{% block navigation %}
    {% include 'home/_navigation.html' %}
{% endblock navigation %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        <div class="vstack gap-2">
            {% csrf_token %}
            {{ import_excel_form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn" href="{% url 'home:prospects-list' %}">Cancel</a>
        </div>
    </form>
{% endblock content %}

home/templates/home/upload_csv_business_data_form.html
{% extends 'home/base.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <form>
        {% csrf_token %}
        {{ yp_fo }}
    </form>
{% endblock content %}